volumes:
  postgres-storage:
    driver: local
  pgadmin-data:
    driver: local

services:
  postgres-db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - 'influxdb-storage:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

